//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesGerman {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesGerman() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Students.Resources.ResourcesGerman", typeof(ResourcesGerman).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Fächer.
        /// </summary>
        public static string AvailableSubjects {
            get {
                return ResourceManager.GetString("AvailableSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Bücher.
        /// </summary>
        public static string AvBooks {
            get {
                return ResourceManager.GetString("AvBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Studienfelder.
        /// </summary>
        public static string AvFieldsOfStudies {
            get {
                return ResourceManager.GetString("AvFieldsOfStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Säle.
        /// </summary>
        public static string AvHalls {
            get {
                return ResourceManager.GetString("AvHalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie dies löschen möchten?.
        /// </summary>
        public static string AYS {
            get {
                return ResourceManager.GetString("AYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück zur Liste.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bücher.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen von Webanwendungen mit ASP.NET Core.
        /// </summary>
        public static string BuildingApp {
            get {
                return ResourceManager.GetString("BuildingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählte Fächer.
        /// </summary>
        public static string ChoosenSubjects {
            get {
                return ResourceManager.GetString("ChoosenSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu erstellen.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu erstellen.
        /// </summary>
        public static string CreateNewBook {
            get {
                return ResourceManager.GetString("CreateNewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch (USA).
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studiengang.
        /// </summary>
        public static string FieldOfStudies {
            get {
                return ResourceManager.GetString("FieldOfStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studiengänge.
        /// </summary>
        public static string FieldsOfStudies {
            get {
                return ResourceManager.GetString("FieldsOfStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etage.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch (Deutschland).
        /// </summary>
        public static string GER {
            get {
                return ResourceManager.GetString("GER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallenummer.
        /// </summary>
        public static string HallNumber {
            get {
                return ResourceManager.GetString("HallNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index des Studenten.
        /// </summary>
        public static string IndexOfStudent {
            get {
                return ResourceManager.GetString("IndexOfStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index des Fachs.
        /// </summary>
        public static string IndexOfSubject {
            get {
                return ResourceManager.GetString("IndexOfSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanisch (Japan).
        /// </summary>
        public static string JPN {
            get {
                return ResourceManager.GetString("JPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfahren Sie mehr über.
        /// </summary>
        public static string LearnAbout {
            get {
                return ResourceManager.GetString("LearnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlesungssaal.
        /// </summary>
        public static string LectureHall {
            get {
                return ResourceManager.GetString("LectureHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlesungssäle.
        /// </summary>
        public static string LectureHalls {
            get {
                return ResourceManager.GetString("LectureHalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptfach.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operationen.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polnisch (Polen).
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postleitzahl.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutz.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzrichtlinie.
        /// </summary>
        public static string PrivacyPolitic {
            get {
                return ResourceManager.GetString("PrivacyPolitic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung der Datenschutzrichtlinie.
        /// </summary>
        public static string PrivacyPoliticDesc {
            get {
                return ResourceManager.GetString("PrivacyPoliticDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name und Nachname des Studenten.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenten.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fach.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fächer.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainisch (Ukraine).
        /// </summary>
        public static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
